In [1]:
#Propiedades de las operaciones de matrices

#Asociativa
 #A*(B*C) = (A*B)*C
    
#Distributiva
 #A*(B+C) = (A*B) + (A*C)

#(OJO, NO ES Commutativa)
 #B*C != C*B


In [2]:
import numpy as np

In [3]:
A = np.array([ [2,3], [5,7], [11,13] ])
B = np.array([ [1,3], [2,1] ])
C = np.array([ [3,1], [4,2] ])

In [9]:
# Asociativa 
ABC = A.dot(B.dot(C))
print(ABC)
print("\n**********\n")
ABC_2 = A.dot(B).dot(C)
print(ABC_2)

[[ 60  26]
 [145  63]
 [295 129]]

**********

[[ 60  26]
 [145  63]
 [295 129]]


In [15]:
# Distributiva 
D = A.dot(B+C)
print(D)

E = (A.dot(B))+(A.dot(C))
print("\n**********\n")
print(E)

print("\n**********\n")

print(D==E)

[[ 26  17]
 [ 62  41]
 [122  83]]

**********

[[ 26  17]
 [ 62  41]
 [122  83]]

**********

[[ True  True]
 [ True  True]
 [ True  True]]


In [19]:
# Conmutativa

F = B.dot(C)
print(F)

print("\n**********\n")

G = C.dot(B)
print(G)

print("\n**********\n")
print(F==G)

[[15  7]
 [10  4]]

**********

[[ 5 10]
 [ 8 14]]

**********

[[False False]
 [False False]]


In [22]:
#Ojo, pero la multiplicacion de vectores si es conmutativa

vector_1 = np.array([[2],[7]])
vector_2 = np.array([[3],[5]])

In [26]:
vector_1_traspuesto = vector_1.T.dot(vector_2)
print(vector_1_traspuesto)
print("\n**********\n")
vector_2_traspuesto = vector_2.T.dot(vector_1)
print(vector_2_traspuesto)


[[41]]

**********

[[41]]
