In [3]:
#Trasposición de un producto de matrices
 #(A*B)^t = B^t * A^t
    
#Recordar: (A*B)^t^t = (A*B)

In [4]:
import numpy as np

In [6]:
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])

In [9]:
print(A.shape)
print(B.shape)

(3, 2)
(2, 2)


In [10]:
AB_traspuesta = (A.dot(B)).T

In [11]:
B_traspuesto_A_traspuesto = (B).T.dot(A.T)

In [12]:
print(AB_traspuesta == B_traspuesto_A_traspuesto)

[[ True  True  True]
 [ True  True  True]]


In [13]:
print(AB_traspuesta)
print('\n*********\n')
print(B_traspuesto_A_traspuesto)


[[ 8 19 37]
 [ 9 22 46]]

*********

[[ 8 19 37]
 [ 9 22 46]]
