In [3]:
import numpy as np

In [4]:
#Matriz Identidad
 #Es el elemento NEUTRO del producto interno (Identidad)

diagonal = np.array([ [1,0,0], [0,1,0], [0,0,1] ])
print(diagonal)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
#Matriz Inversa
 #Es la cual, al multiplicarse por su NO inversa,
 #se obtiene la identidad -> A*A_Inversa = Identidad

In [8]:
#Matriz Singular
 #La cual NO existe su inversa


In [9]:
#Matriz diagonal

vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [13]:
#Matriz diagonal NO cuadrada
print(matriz[0:4,0:3])
print("\n")

#o también...
print(matriz[0:3,0:4])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [14]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [17]:
v1 = np.array([[1,1,1,1]])
print(v1)

print("\n")

print(A.dot(v1.T))

[[1 1 1 1]]


[[2]
 [3]
 [4]
 [5]]


In [24]:
A_inv = np.diag([1/2,1/3, 1/4, 1/5])

print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [25]:
#Manualmente calculamos la matriz inversa

identidad = A.dot(A_inv)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
#Lo corroboramos con el metodo de linear algebra de python

A_inv_calc = np.linalg.inv(A)

print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [28]:
#MATRIZ SIMÉTRICA
 #Es cuando su traspuesta es igual a la matriz
 #A = A_traspuesta
 #entonces... matriz diagonal = matriz simétrica

In [30]:
#SIMETRICA

print(A.T)
print("\n")
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [32]:
simetrica = np.array([ [1,2,3], [2,-1,7], [3,7,11] ])

print(simetrica)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [33]:
print(simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
