In [1]:
#MATRIZ ORTOGONAL
#Es cuando todas sus filas son mutuamente ortoNormales
#y todas sus columnas son mutuamente ortoNormales


In [2]:
import numpy as np

In [3]:
matriz = np.array([[1,0,0],
                  [0,1,0],
                  [0,0,1]])

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
#Primera fila por la segunda fila
print(matriz[:,0].dot(matriz[:,1]))
print(matriz[:,0].dot(matriz[:,2]))
print(matriz[:,1].dot(matriz[:,2]))

0
0
0


In [7]:
print(np.linalg.norm(matriz[:,0]))
print(np.linalg.norm(matriz[:,1]))
print(np.linalg.norm(matriz[:,2]))


1.0
1.0
1.0


In [8]:
#Cumplió parte de los requerimientos, ahora nos falta comprobar
#que las filas sean ortonormales

In [11]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [12]:
print(np.linalg.norm(matriz[0,:]))
print(np.linalg.norm(matriz[1,:]))
print(np.linalg.norm(matriz[2,:]))

1.0
1.0
1.0


In [13]:
#Manera sencilla de generar matrices ortogonales 

In [14]:
A = np.array([[np.cos(100), -np.sin(100)],
             [np.sin(100), np.cos(100)]])

print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [16]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

1.0
1.0
1.0
1.0


In [18]:
#Calculando productos internos por filas y columnas
print(A[0,:].dot(A[1,:]))
print(A[:,0].dot(A[:,1]))

0.0
0.0


In [21]:
A_t = A.T 
print(A_t.dot(A))
print("\n")
print(A.dot(A_t))

[[ 1.00000000e+00 -8.64444332e-18]
 [-8.64444332e-18  1.00000000e+00]]


[[1.00000000e+00 8.64444332e-18]
 [8.64444332e-18 1.00000000e+00]]


In [22]:
#Traspuesta e inversa son iguales

A_inv = np.linalg.inv(A)
print(A_inv)

print("\n")

print(A_t)

[[ 0.86231887 -0.50636564]
 [ 0.50636564  0.86231887]]


In [24]:
#Hay que tener cuidado para no dividir el producto de las traspuesta
#por la matriz sin haber definido el limite ya que ese -8.64..e-18
#en realidad es un numero muy cercano a 0 y al no serlo
#el pc lo amplifico demasiado al dividirlo el 1 por lo anterior
#si hubiera sido 0 la operacion hubiera sido "NO definida"
print(1/A_t.dot(A))

[[ 1.00000000e+00 -1.15681249e+17]
 [-1.15681249e+17  1.00000000e+00]]
